[tool.black]
line-length = 120
target-version = ["py310"]
extend-exclude = '''
(?x)(
  ultralytics-main/
  | \.venv/
  | model/
  | static/
  | \.ipynb$
)
'''

[tool.ruff]
line-length = 120
target-version = "py310"
extend-exclude = [
  "ultralytics-main",
  ".venv",
  "model",
  "static",
]
