[tool.black]
line-length = 120
target-version = ["py310"]
exclude = '''
(?x)(
  ^ultralytics-main/
  |^\.venv/
  |^model/
  |^static/
)
'''

[tool.ruff]
line-length = 120
target-version = "py310"
extend-exclude = [
  "ultralytics-main",
  ".venv",
  "model",
  "static",
]
